
server:
  port: 8783
spring:
  application:
    name: service-hi-ha
  security:
    user:
      name: user
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
info:
  app.name: Client1